Book component
wolox-training/jv-react-native pull request #5
Opened 2020-11-05 01:42 UTC by Vente16

## Summary

Creation of `Book` component 

`## Screenshots

### Android
#### Galaxy

![galaxy](https://user-images.githubusercontent.com/22964999/98186661-40480700-1edd-11eb-83dc-f2f23aec975d.png)

#### Pixel 2/3

- Pixel 2

![pixel-2](https://user-images.githubusercontent.com/22964999/98185913-9fa51780-1edb-11eb-8e85-d8b8a56f3e18.png)

-Pixel 3

![pixel-3](https://user-images.githubusercontent.com/22964999/98185935-ad5a9d00-1edb-11eb-9808-9f9d7588bc28.png)

### iOS
#### iPhone SE
![Iphone-SE](https://user-images.githubusercontent.com/22964999/98185769-4e952380-1edb-11eb-9ed9-08ad440e81d4.png)

#### iPhone 8/11

- iPhone 11

![Iphone-11](https://user-images.githubusercontent.com/22964999/98185786-5785f500-1edb-11eb-9c26-58a97250a8bd.png)

- iPhone 8

![Iphone-8](https://user-images.githubusercontent.com/22964999/98185832-6f5d7900-1edb-11eb-931c-bffba5b41d2b.png)

## Trello Card

https://trello.com/c/eh7iA5jz/10-n22-componente-libro

2020-11-05 15:45 UTC, mcavo requested changes
Great work!! 💪 🎉  🥇 
Just some suggestions!

2020-11-05 15:45 UTC, mcavo commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +                    source={ { uri: (imageUrl) ? `${imageUrl}` : 'https://reactnative.dev/img/tiny_logo.png' } }
This parenthesis are unnecesary 😄 
```suggestion
                    source={ { uri: imageUrl ? `${imageUrl}` : 'https://reactnative.dev/img/tiny_logo.png' } }
```

2020-11-05 15:45 UTC, mcavo commented on wbooks/src/app/screens/Library/components/Book/styles.ts
> +        color: '#4A4A4A',
you can extract colors into `@constants/colors` that way you would be able to easily use them everywhere and it would make any app rebranding easy 😄 
The same could be done for spacings also

2020-11-05 15:45 UTC, mcavo commented on wbooks/src/app/styles.ts
> +      backgroundColor: '#EAF6FA',
Same 😄

2020-11-05 15:45 UTC, mcavo commented on wbooks/src/interfaces/book.ts
> +    imageUrl: string | null;
we won't use `image?: string`? Just a question 😄

2020-11-05 15:45 UTC, mcavo commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +import { Book as BookInterface } from '@interfaces/book';
Some convention very popular is to use `I` as a prefix for interfaces, like `IBook`, but I would try to avoid renaming if you can, that way you don't have any future problems with auto import things 😄

2020-11-05 15:45 UTC, mcavo commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +                    <Text style={styles.titleBook}>{title}</Text>
You might want to have just one line for the title, to avoid having Books of different sizes in the cases where the title or the text are way too long

2020-11-05 16:48 UTC, Vente16 commented on wbooks/src/interfaces/book.ts
> +    imageUrl: string | null;
Sorry, I tried use  `imageUrl?: string`, but vs code show me one issue

![Screen Shot 2020-11-05 at 11 45 05 AM](https://user-images.githubusercontent.com/22964999/98269987-69f44300-1f5c-11eb-8a63-21010b83a4b2.png)


I see this one

![Screen Shot 2020-11-05 at 11 28 27 AM](https://user-images.githubusercontent.com/22964999/98269476-c5720100-1f5b-11eb-8f62-5b0ace0d7dbf.png)

I'm not sure what can it's

2020-11-05 16:50 UTC, Vente16 commented on wbooks/src/app/screens/Library/components/Book/index.tsx
> +import { Book as BookInterface } from '@interfaces/book';
Thanks, sounds good!

2020-11-05 16:55 UTC, Vente16 commented on wbooks/src/app/screens/Library/components/Book/styles.ts
> +        color: '#4A4A4A',
Cool, I think that so it's better

2020-11-06 15:55 UTC, sfernandez11 requested changes
Great work! Just one comment...

2020-11-06 15:55 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/components/Book/styles.ts
> +    paddingBottom: 85,
Check with [Marvel](https://marvelapp.com/prototype/b3fe593/screen/71449379/handoff), these spacings are not ok (for example: `margin: 25` 🔴  => `marginHorizontal: 20`  and `marginVertical: 10`, ¿¿¿ `paddingBottom: 85` ???)
Also, don't use `padding` and `paddingBottom`, for this case you only need `paddingVertical` and `paddingHorizontal`

2020-11-06 21:51 UTC, sfernandez11 approved these changes
🥇

2020-11-09 14:35 UTC, mcavo approved these changes
Great work!!
![](https://media.giphy.com/media/MAzunB1Ru6zAYlYgPD/giphy.gif)

2020-11-09 14:54 UTC, merged