Ui list books
wolox-training/jv-react-native pull request #7
Opened 2020-11-09 17:32 UTC by Vente16

## Summary

List of books, this component content FlatList component and its props

## Screenshots

### Android

#### Galaxy S (or similar)

![galaxy-list](https://user-images.githubusercontent.com/22964999/98572541-c40a4680-2283-11eb-86db-37feb78c3646.png)

#### Pixel 2 

![pixel-2-list](https://user-images.githubusercontent.com/22964999/98572598-ce2c4500-2283-11eb-8a50-8ea33e048949.png)

#### Pixel 3 
![pixel-3-list](https://user-images.githubusercontent.com/22964999/98572637-d8e6da00-2283-11eb-8edb-ad2b596d7837.png)

### iOS

#### iPhone SE 
![Iphone-SE](https://user-images.githubusercontent.com/22964999/98572686-e56b3280-2283-11eb-9e56-31a8e99dec88.png)

#### iPhone 8
![Iphone-8](https://user-images.githubusercontent.com/22964999/98572705-ebf9aa00-2283-11eb-9d25-8f495a7bb7f6.png)

#### iPhone 11
![Iphone-11](https://user-images.githubusercontent.com/22964999/98574377-d84f4300-2285-11eb-8ece-6417af0404c2.png)

## Trello Card

https://trello.com/c/hYAyiyqN/9-n23-lista-de-libros

2020-11-09 18:14 UTC, mcavo requested changes
Great work! Just one comment!

2020-11-09 18:14 UTC, mcavo commented on wbooks/src/app/screens/Library/index.tsx
> +  return <FlatList data={BOOKS_MOCK} renderItem={renderBook} keyExtractor={item => `${item.id}`} />;
I would be consistent, extracting both renderItem and keyExtractor methods into constants or using directly there

Personally I don't mind in this case to not extract them into constants because in both cases the method is being redefined again in each render, also the methods aren't complex enough to affect the readability of the props

Also, you can spread item in keyExtractor:
```
keyExtractor={{ id } => `${id}`}
```

2020-11-09 18:35 UTC, sfernandez11 commented on wbooks/src/app/index.tsx
>        </SafeAreaView>
Move the `SafeAreaView` inside the `Library` screen and you can delete the `src/app/styles.ts` file

2020-11-09 20:07 UTC, sfernandez11 requested changes

2020-11-09 20:07 UTC, sfernandez11 commented on wbooks/src/app/index.tsx
> -      <StatusBar barStyle="dark-content" />
Don't move the `StatusBar`, I said only the `SafeAreaView`. The `SafeAreaView` is for the screen and the `StatusBar` is for the App

2020-11-09 20:07 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        <FlatList data={BOOKS_MOCK} renderItem={renderBook} keyExtractor={({ id }) => `${id}`} />
You forgot to extract the `keyExtractor` function as `renderBook`

2020-11-09 20:40 UTC, Vente16 commented on wbooks/src/app/screens/Library/index.tsx
> +        <FlatList data={BOOKS_MOCK} renderItem={renderBook} keyExtractor={({ id }) => `${id}`} />
I don't understand this. Create a function for prop `keyExtractor` like `renderBook` ?

2020-11-09 21:20 UTC, sfernandez11 commented on wbooks/src/app/screens/Library/index.tsx
> +        <FlatList data={BOOKS_MOCK} renderItem={renderBook} keyExtractor={({ id }) => `${id}`} />
Exactly 😄 Something like this: `const keyExtractor = ({ id }: Book) => String(id);` works too

2020-11-09 21:59 UTC, sfernandez11 reviewed
Last comment

2020-11-09 21:59 UTC, sfernandez11 commented on wbooks/src/app/index.tsx
> +import { StatusBar } from 'react-native';
Sort imports, global imports first!

2020-11-10 14:13 UTC, sfernandez11 approved these changes
🥇

2020-11-10 17:53 UTC, merged